CREATE TABLE IF NOT EXISTS reporting_invoice_line_fact (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    source_line_id INT NOT NULL,
    source_invoice_id INT NOT NULL,
    invoice_number VARCHAR(64) NOT NULL,
    invoice_date DATE NOT NULL,
    invoice_datetime DATETIME NOT NULL,
    product_id INT NOT NULL,
    product_code VARCHAR(50) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    customer_id INT NULL,
    seller_id INT NULL,
    prestataire_id INT NULL,
    representative_id INT NULL,
    site_id INT NULL,
    mode_vente VARCHAR(10) NULL,
    channel_code VARCHAR(10) NULL,
    channel_name VARCHAR(50) NULL,
    web_flag TINYINT(1) NULL,
    no_web_flag INT NULL,
    quantity DECIMAL(12,3) NOT NULL DEFAULT 0,
    unit_price_ttc DECIMAL(10,2) NOT NULL DEFAULT 0,
    total_ht DECIMAL(10,2) NOT NULL DEFAULT 0,
    total_ttc DECIMAL(10,2) NOT NULL DEFAULT 0,
    margin_ht DECIMAL(10,2) NOT NULL DEFAULT 0,
    discount_percent DECIMAL(4,2) NOT NULL DEFAULT 0,
    discount_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    tax_rate DECIMAL(4,2) NOT NULL DEFAULT 0,
    raw_origin VARCHAR(2) NULL,
    raw_type_piece VARCHAR(10) NULL,
    imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_source_line_id (source_line_id),
    KEY idx_invoice_date (invoice_date),
    KEY idx_source_invoice_id (source_invoice_id),
    KEY idx_product_id (product_id),
    KEY idx_customer_id (customer_id),
    KEY idx_channel_name (channel_name),
    KEY idx_invoice_date_channel (invoice_date, channel_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
